CH2=chapter2-a-tour-of-cpp-the-basics
CH4=chapter4-a-tour-of-cpp-containers-and-algorithms

default:
	echo "\n============\n" \
	"Hello, <tab> key will be extremely helpful to execute the examples.\n\n" \
	"e.g.,\n"\
	"make 2<tab><tab>: shows examples of chapter 2\n"

2-2-1-hello:
	$(MAKE) -C $(CH2) $@

2-2-4-y-or-n:
	$(MAKE) -C $(CH2) $@

2-2-5-print-and-count:
	$(MAKE) -C $(CH2) $@

2-3-1-vector-sum:
	$(MAKE) -C $(CH2) $@

2-3-2-vector-sum:
	$(MAKE) -C $(CH2) $@

2-3-3-traffic-lights:
	$(MAKE) -C $(CH2) $@

2-4-1-vector-sqrt-sum:
	$(MAKE) -C $(CH2) $@

2-4-3-error-handling:
	$(MAKE) -C $(CH2) $@


4-2-string:
	$(MAKE) -C $(CH4) $@

4-3-streamio:
	$(MAKE) -C $(CH4) $@

4-4-1-vector:
	$(MAKE) -C $(CH4) $@

4-4-1-2-range-check:
	$(MAKE) -C $(CH4) $@

4-4-2-list:
	$(MAKE) -C $(CH4) $@

4-4-3-map:
	$(MAKE) -C $(CH4) $@

4-4-4-unordered-map:
	$(MAKE) -C $(CH4) $@

4-5-algorithms:
	$(MAKE) -C $(CH4) $@

4-5-1-find-all:
	$(MAKE) -C $(CH4) $@

4-5-3-io-iterators:
	$(MAKE) -C $(CH4) $@

4-5-4-predicates:
	$(MAKE) -C $(CH4) $@

4-5-6-sort:
	$(MAKE) -C $(CH4) $@


clean:
	$(MAKE) -C $(CH2) $@
	$(MAKE) -C $(CH4) $@
