CH2=chapter2-a-tour-of-cpp-the-basics

default:
	echo "\n============\n" \
	"Hello, <tab> key will be extremely helpful to execute the examples.\n\n" \
	"e.g.,\n"\
	"make 2<tab><tab>: shows examples of chapter 2\n"

2-2-1-hello:
	$(MAKE) -C $(CH2) $@

2-2-4-y-or-n:
	$(MAKE) -C $(CH2) $@

2-2-5-print-and-count:
	$(MAKE) -C $(CH2) $@

2-3-1-vector-sum:
	$(MAKE) -C $(CH2) $@

2-3-2-vector-sum:
	$(MAKE) -C $(CH2) $@

2-3-3-traffic-lights:
	$(MAKE) -C $(CH2) $@

2-4-1-vector-sqrt-sum:
	$(MAKE) -C $(CH2) $@

2-4-3-error-handling:
	$(MAKE) -C $(CH2) $@

clean:
	$(MAKE) -C $(CH2) $@
